# Generated by Django 5.2 on 2025-04-22 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimatehistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Estimate History', 'verbose_name_plural': 'Estimate Histories'},
        ),
        migrations.AlterField(
            model_name='estimatehistory',
            name='bhk',
            field=models.IntegerField(help_text='Number of bedrooms (BHK)', validators=[django.core.validators.MinValueValidator(1, message='BHK must be at least 1'), django.core.validators.MaxValueValidator(6, message='BHK cannot exceed 6')]),
        ),
        migrations.AlterField(
            model_name='estimatehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when estimate was made'),
        ),
        migrations.AlterField(
            model_name='estimatehistory',
            name='location',
            field=models.CharField(help_text='Location/area of the property', max_length=100),
        ),
        migrations.AlterField(
            model_name='estimatehistory',
            name='predicted_rent',
            field=models.FloatField(help_text='Model-predicted monthly rent', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estimatehistory',
            name='sqft',
            field=models.FloatField(help_text='Built-up area in square feet', validators=[django.core.validators.MinValueValidator(100, message='Area must be at least 100 sqft'), django.core.validators.MaxValueValidator(10000, message='Area cannot exceed 10000 sqft')]),
        ),
        migrations.AlterField(
            model_name='estimatehistory',
            name='user_id',
            field=models.CharField(help_text='Firebase UID of the user', max_length=128),
        ),
        migrations.AddIndex(
            model_name='estimatehistory',
            index=models.Index(fields=['-created_at'], name='authenticat_created_8df9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatehistory',
            index=models.Index(fields=['user_id', '-created_at'], name='authenticat_user_id_a2fb1b_idx'),
        ),
    ]
